language: r

# Use sudo-enabled environment for better package installation
sudo: required

# Set R version (optional)
r:
  - release

# Install required R packages
r_packages:
  - httr
  - jsonlite
  - testthat  # For testing your API functions

# Set environment variables for API authentication (secure credentials)
env:
  global:
    - CLIENT_ID=your_client_id_here
    - CLIENT_SECRET=your_client_secret_here
    - REDDIT_USERNAME=your_reddit_username_here
    - REDDIT_PASSWORD=your_reddit_password_here

# Before running tests, source necessary scripts
before_script:
  - Rscript -e 'source("./R/reddit_auth.R")'
  - Rscript -e 'source("./R/get_subreddit_info.R")'
  - Rscript -e 'source("./R/get_subreddit_posts.R")'
  - Rscript -e 'source("./R/get_post_comments.R")'

# Run tests using testthat (ensure you have test files in "tests/testthat/")
script:
  - Rscript -e 'testthat::test_dir("tests/testthat/")'

# Only build the master branch
branches:
  only:
    - master

# Cache R packages to speed up builds
cache: packages
