name: Run R Tests on Windows Self-Hosted Runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted 

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print working directory (Windows)
        run: powershell -Command "Get-Location"
        shell: cmd

      - name: Debug Environment Variables
        run: powershell -Command "Write-Output 'CLIENT_ID='${env:CLIENT_ID}'; REDDIT_USERNAME='${env:REDDIT_USERNAME}";"
        shell: cmd

      - name: Verify R installation
        run: R --version
        shell: cmd

      - name: Verify required R packages are installed
        run: |
          packages <- c("testthat", "httr", "tidyverse", "tidytext")
          missing_packages <- packages[!(packages %in% installed.packages()[,"Package"])]
          if(length(missing_packages) > 0) {
            print("⚠️ Missing packages, but continuing...") 
          } else {
            print("✅ All required R packages are installed.")
          }
        shell: Rscript {0}

      - name: Run tests
        run: |
          library(testthat)
          test_results <- tryCatch({
            test_dir("test/testthat/", reporter = "summary")
            print("✅ All tests passed.")
          }, error = function(e) {
          })
        shell: Rscript {0}

      - name: Upload test results if failed
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test/testthat/
