name: Run R Tests on Windows Self-Hosted Runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted  # 运行在本地 Windows 机器

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print working directory (Windows)
        run: powershell -Command "Get-Location"
        shell: cmd

      - name: Debug Environment Variables
        run: powershell -Command "Write-Output 'CLIENT_ID='${env:CLIENT_ID}'; REDDIT_USERNAME='${env:REDDIT_USERNAME}"
        shell: cmd

      - name: Verify R installation
        run: R --version
        shell: cmd

      - name: Verify required R packages are installed
        run: |
          packages <- c("testthat", "httr", "tidyverse", "tidytext")
          missing_packages <- packages[!(packages %in% installed.packages()[,"Package"])]
          if(length(missing_packages) > 0) {
            stop("ERROR: The following packages are missing: ", paste(missing_packages, collapse = ", "))
          } else {
            print("All required R packages are installed.")
          }
        shell: Rscript {0}

      - name: Run tests
        run: |
          library(testthat)
          test_dir("tests/testthat/", reporter = "summary")
        shell: Rscript {0}

      - name: Upload test results if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/testthat/
